UHF-9718: Markdown table

diff --git a/.github/workflows/update-config.yml b/.github/workflows/update-config.yml
--- a/.github/workflows/update-config.yml
+++ b/.github/workflows/update-config.yml
@@ -55,7 +55,9 @@ jobs:
         id: module-status
         run: |
           MODE="delete"
-          drush helfi:tools:check-composer-versions $GITHUB_WORKSPACE/composer.lock > /tmp/pr-message.txt && EXIT_CODE=$? || EXIT_CODE=$?
+          echo "Failed to install the latest version of the following packages:\n" > /tmp/pr-message.txt
+          drush helfi:tools:check-composer-versions $GITHUB_WORKSPACE/composer.lock --format=markdown_table >> /tmp/pr-message.txt && EXIT_CODE=$? || EXIT_CODE=$?
+          echo "Please run `composer why-not drupal/package_name package_version`\n." >> /tmp/pr-message.txt
           if [ "$EXIT_CODE" -eq 3 ]; then
             MODE="upsert"
           fi
